In [1]:
import torch

### 4.1 텐서

#### 4.1.1 Scalar

In [35]:
scalar1 = torch.tensor([1.])
print(scalar1)

scalar2 = torch.tensor([3.])
print(scalar2)

tensor([1.])
tensor([3.])


In [9]:
add_scalar = scalar1 + scalar2
print(add_scalar)

add_scalar = scalar1 - scalar2
print(add_scalar)

add_scalar = scalar1 * scalar2
print(add_scalar)

add_scalar = scalar1 / scalar2
print(add_scalar)

tensor([4.])
tensor([-2.])
tensor([3.])
tensor([0.3333])


In [12]:
torch.add(scalar1,scalar2)
torch.sub(scalar1,scalar2)
torch.mul(scalar1,scalar2)
torch.div(scalar1,scalar2)

tensor([0.3333])

#### 4.1.2 Vector

In [17]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

vector2 = torch.tensor([4., 5., 6.])
print(vector1)

tensor([1., 2., 3.])
tensor([1., 2., 3.])


In [18]:
add_vector = vector1 + vector2
print(add_vector)

sub_vector = vector1 - vector2
print(sub_vector)

mul_vector = vector1 * vector2
print(mul_vector)

div_vector = vector1 / vector2
print(div_vector)

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])


In [22]:
torch.add(vector1, vector2)
torch.sub(vector1, vector2)
torch.mul(vector1, vector2)
torch.div(vector1, vector2)
torch.dot(vector1, vector2) # 내적의 합

tensor(32.)

#### 4.1.3 Matrix(행렬)

In [25]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [39]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

sub_matrix = matrix1 - matrix2
print(sub_matrix)

mul_matrix = matrix1 * matrix2
print(sum_matrix)

div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [40]:
torch.add(matrix1, matrix2)
torch.sub(matrix1, matrix2)
torch.mul(matrix1, matrix2)
torch.div(matrix1, matrix2)
torch.matmul(matrix1, matrix2) # 내적

tensor([[19., 22.],
        [43., 50.]])

#### 4.1.4 텐서

In [42]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7.,8.]]])
print(tensor1)

tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15.,16.]]])
print(tensor2)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [44]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

sub_tensor = tensor1 - tensor2
print(sub_tensor)

mul_tensor = tensor1 * tensor2
print(mul_tensor)

div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])
tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [45]:
torch.add(tensor1, tensor2)
torch.sub(tensor1, tensor2)
torch.mul(tensor1, tensor2)
torch.div(tensor1, tensor2)
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

### 4.2 Autograd

In [49]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')
DEVICE

device(type='cpu')

In [66]:
BATCH_SIZE = 64   # 계산되는 데이터 개수 = 즉, input이 64개라고 가정
INPUT_SIZE = 1000 # 입력층의 노드 수 (64, 1000)
HIDDEN_SIZE = 100 # 계산되는 파라미터 수 (1000, 100)
OUTPUT_SIZE = 10  # 10 크기의 분류

In [91]:
x = torch.randn(BATCH_SIZE,      # (64, 1000)으로 생성
               INPUT_SIZE, 
               device = DEVICE, 
               dtype = torch.float,
               requires_grad = False) # ? 

y = torch.randn(BATCH_SIZE,    # (64, 10)
               OUTPUT_SIZE, 
               device = DEVICE, 
               dtype = torch.float,
               requires_grad = False)

w1 = torch.randn(INPUT_SIZE,    # (1000, 100)
               HIDDEN_SIZE, 
               device = DEVICE, 
               dtype = torch.float,
               requires_grad = True)

w2 = torch.randn(HIDDEN_SIZE,   # (100, 10)
               OUTPUT_SIZE, 
               device = DEVICE, 
               dtype = torch.float,
               requires_grad = True)

In [92]:
learning_rate = 1e-06

for t in range(1, 501):
    y_pred = x.mm(w1).clamp(min = 0).mm(w2) # 곱하여 비선형함수 적용, = ReLU()
    
    loss = (y_pred - y).pow(2).sum() # pow  제곱 합
    if t % 100 == 0:
        print("Iteration : ", t, "\t", "Loss :" , loss.item())

    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        w1.grad.zero_()
        w2.grad.zero_()

Iteration :  100 	 Loss : 490.12890625
Iteration :  200 	 Loss : 2.2500107288360596
Iteration :  300 	 Loss : 0.01625542715191841
Iteration :  400 	 Loss : 0.0003451093507464975
Iteration :  500 	 Loss : 5.283463542582467e-05
